//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: cmd_type.proto
namespace PROTO_CMD_TYPE
{
    [global::ProtoBuf.ProtoContract(Name=@"CMD_TYPE")]
    public enum CMD_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ACCOUNT", Value=10)]
      CMD_TYPE_ACCOUNT = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ROLE", Value=11)]
      CMD_TYPE_ROLE = 11
    }
  
}