//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: role.proto
namespace PROTO_ROLE
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCM_CREATE_ROLE")]
  public partial class TCM_CREATE_ROLE : global::ProtoBuf.IExtensible
  {
    public TCM_CREATE_ROLE() {}
    
    private string _RoleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoleName
    {
      get { return _RoleName; }
      set { _RoleName = value; }
    }
    private uint _HeadIcon;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"HeadIcon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint HeadIcon
    {
      get { return _HeadIcon; }
      set { _HeadIcon = value; }
    }
    private bool _IsUnion = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"IsUnion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsUnion
    {
      get { return _IsUnion; }
      set { _IsUnion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCM_CHANGE_ROLE_NAME")]
  public partial class TCM_CHANGE_ROLE_NAME : global::ProtoBuf.IExtensible
  {
    public TCM_CHANGE_ROLE_NAME() {}
    
    private string _RoleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoleName
    {
      get { return _RoleName; }
      set { _RoleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCM_CHANGE_ICON")]
  public partial class TCM_CHANGE_ICON : global::ProtoBuf.IExtensible
  {
    public TCM_CHANGE_ICON() {}
    
    private int _icon;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_CREATE_ROLE")]
  public partial class TSM_CREATE_ROLE : global::ProtoBuf.IExtensible
  {
    public TSM_CREATE_ROLE() {}
    
    private uint _Error;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Error
    {
      get { return _Error; }
      set { _Error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_CHANGE_ROLE_NAME")]
  public partial class TSM_CHANGE_ROLE_NAME : global::ProtoBuf.IExtensible
  {
    public TSM_CHANGE_ROLE_NAME() {}
    
    private uint _Error;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Error
    {
      get { return _Error; }
      set { _Error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TcltRoleInfo")]
  public partial class TcltRoleInfo : global::ProtoBuf.IExtensible
  {
    public TcltRoleInfo() {}
    
    private string _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Exp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private uint _Gold;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Gold
    {
      get { return _Gold; }
      set { _Gold = value; }
    }
    private uint _BunkerLV;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"BunkerLV", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BunkerLV
    {
      get { return _BunkerLV; }
      set { _BunkerLV = value; }
    }
    private uint _HeadIcon;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"HeadIcon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint HeadIcon
    {
      get { return _HeadIcon; }
      set { _HeadIcon = value; }
    }
    private uint _HeadFrame;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"HeadFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint HeadFrame
    {
      get { return _HeadFrame; }
      set { _HeadFrame = value; }
    }
    private uint _PveMoney;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"PveMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PveMoney
    {
      get { return _PveMoney; }
      set { _PveMoney = value; }
    }
    private uint _PvpMoney;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"PvpMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PvpMoney
    {
      get { return _PvpMoney; }
      set { _PvpMoney = value; }
    }
    private uint _NumberID;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"NumberID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NumberID
    {
      get { return _NumberID; }
      set { _NumberID = value; }
    }
    private ulong _CreateTime;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"CreateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong CreateTime
    {
      get { return _CreateTime; }
      set { _CreateTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_ROLE_INFO")]
  public partial class TSM_ROLE_INFO : global::ProtoBuf.IExtensible
  {
    public TSM_ROLE_INFO() {}
    
    private PROTO_ROLE.TcltRoleInfo _RoleInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PROTO_ROLE.TcltRoleInfo RoleInfo
    {
      get { return _RoleInfo; }
      set { _RoleInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_EXP")]
  public partial class TSM_EXP : global::ProtoBuf.IExtensible
  {
    public TSM_EXP() {}
    
    private uint _exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_GOLD")]
  public partial class TSM_GOLD : global::ProtoBuf.IExtensible
  {
    public TSM_GOLD() {}
    
    private uint _gold;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_LEVEL")]
  public partial class TSM_LEVEL : global::ProtoBuf.IExtensible
  {
    public TSM_LEVEL() {}
    
    private uint _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_BUNKER_LEVEL")]
  public partial class TSM_BUNKER_LEVEL : global::ProtoBuf.IExtensible
  {
    public TSM_BUNKER_LEVEL() {}
    
    private uint _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_LOCK_INFO")]
  public partial class TSM_LOCK_INFO : global::ProtoBuf.IExtensible
  {
    public TSM_LOCK_INFO() {}
    
    private ulong _UnLockTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UnLockTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UnLockTime
    {
      get { return _UnLockTime; }
      set { _UnLockTime = value; }
    }
    private string _Reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Reason
    {
      get { return _Reason; }
      set { _Reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_ROLE_NAME")]
  public partial class TSM_ROLE_NAME : global::ProtoBuf.IExtensible
  {
    public TSM_ROLE_NAME() {}
    
    private string _Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_CHANGE_HEAD_ICON_RESULT")]
  public partial class TSM_CHANGE_HEAD_ICON_RESULT : global::ProtoBuf.IExtensible
  {
    public TSM_CHANGE_HEAD_ICON_RESULT() {}
    
    private PROTO_ROLE.EChangeHeadIconError _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PROTO_ROLE.EChangeHeadIconError result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_CHANGE_HEAD_FRAME_RESULT")]
  public partial class TSM_CHANGE_HEAD_FRAME_RESULT : global::ProtoBuf.IExtensible
  {
    public TSM_CHANGE_HEAD_FRAME_RESULT() {}
    
    private PROTO_ROLE.EChangeHeadIconError _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PROTO_ROLE.EChangeHeadIconError result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_UPDATE_HEAD_ICON")]
  public partial class TSM_UPDATE_HEAD_ICON : global::ProtoBuf.IExtensible
  {
    public TSM_UPDATE_HEAD_ICON() {}
    
    private uint _head_icon;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"head_icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint head_icon
    {
      get { return _head_icon; }
      set { _head_icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_UPDATE_HEAD_FRAME")]
  public partial class TSM_UPDATE_HEAD_FRAME : global::ProtoBuf.IExtensible
  {
    public TSM_UPDATE_HEAD_FRAME() {}
    
    private uint _head_frame;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"head_frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint head_frame
    {
      get { return _head_frame; }
      set { _head_frame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_PVEMONEY")]
  public partial class TSM_PVEMONEY : global::ProtoBuf.IExtensible
  {
    public TSM_PVEMONEY() {}
    
    private uint _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_PVPMONEY")]
  public partial class TSM_PVPMONEY : global::ProtoBuf.IExtensible
  {
    public TSM_PVPMONEY() {}
    
    private uint _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CLT_CMD")]
    public enum CLT_CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_CREATE_ROLE", Value=1)]
      CM_CREATE_ROLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_CHANGE_NAME", Value=2)]
      CM_CHANGE_NAME = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_CHANGE_HEAD_ICON", Value=3)]
      CM_CHANGE_HEAD_ICON = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_CHANGE_HEAD_FRAME", Value=4)]
      CM_CHANGE_HEAD_FRAME = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SVR_CMD")]
    public enum SVR_CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_NO_ROLE", Value=1)]
      SM_NO_ROLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_CREATE_ROLE", Value=2)]
      SM_CREATE_ROLE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_ROLE_INFO", Value=3)]
      SM_ROLE_INFO = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_EXP", Value=4)]
      SM_EXP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_GOLD", Value=5)]
      SM_GOLD = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_LEVEL", Value=6)]
      SM_LEVEL = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_BUNKER_LEVEL", Value=7)]
      SM_BUNKER_LEVEL = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_LOCK_INFO", Value=8)]
      SM_LOCK_INFO = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_CHANGE_ICON_RESULT", Value=9)]
      SM_CHANGE_ICON_RESULT = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_UPDATE_HEAD_ICON", Value=10)]
      SM_UPDATE_HEAD_ICON = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_CHANGE_FRAME_RESULT", Value=11)]
      SM_CHANGE_FRAME_RESULT = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_UPDATE_HEAD_FRAME", Value=12)]
      SM_UPDATE_HEAD_FRAME = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_CHANGE_RESULT", Value=13)]
      SM_CHANGE_RESULT = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_CHANGE_ROLENAME", Value=14)]
      SM_CHANGE_ROLENAME = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_PVEMONEY", Value=15)]
      SM_PVEMONEY = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_PVPMONEY", Value=16)]
      SM_PVPMONEY = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_SERVER_CFG_NO_ROLE", Value=17)]
      SM_SERVER_CFG_NO_ROLE = 17
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LIMIT")]
    public enum LIMIT
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIMIT_GOLD", Value=99999999)]
      LIMIT_GOLD = 99999999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIMIT_PVEMONEY", Value=99999999)]
      LIMIT_PVEMONEY = 99999999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIMIT_PVPMONEY", Value=99999999)]
      LIMIT_PVPMONEY = 99999999
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ECreateRoleError")]
    public enum ECreateRoleError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eCreateRoleError_NameInvalid", Value=1)]
      eCreateRoleError_NameInvalid = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eCreateRoleError_NameExist", Value=2)]
      eCreateRoleError_NameExist = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EChangeRoleError")]
    public enum EChangeRoleError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eChangeRoleError_NameInvalid", Value=1)]
      eChangeRoleError_NameInvalid = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eChangeRoleError_NameExist", Value=2)]
      eChangeRoleError_NameExist = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eChangeRoleError_Diamond", Value=3)]
      eChangeRoleError_Diamond = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EChangeHeadIconError")]
    public enum EChangeHeadIconError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eChangeHeadIconError_invalid", Value=1)]
      eChangeHeadIconError_invalid = 1
    }
  
}