//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: account.proto
namespace PROTO_ACCOUNT
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCM_ACCOUNT_INFO")]
  public partial class TCM_ACCOUNT_INFO : global::ProtoBuf.IExtensible
  {
    public TCM_ACCOUNT_INFO() {}
    
    private string _AccountID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AccountID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AccountID
    {
      get { return _AccountID; }
      set { _AccountID = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CLT_CMD")]
    public enum CLT_CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_LOGIN", Value=1)]
      CM_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_REGIST", Value=2)]
      CM_REGIST = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SVR_CMD")]
    public enum SVR_CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_LONGIN_SUCCESSED", Value=1)]
      SM_LONGIN_SUCCESSED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_LONGIN_FAILED", Value=2)]
      SM_LONGIN_FAILED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_REGISTER_SUCCESSED", Value=3)]
      SM_REGISTER_SUCCESSED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_REGISTER_FAILED", Value=4)]
      SM_REGISTER_FAILED = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ERegisterError")]
    public enum ERegisterError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eRegisterError_AccountExist", Value=1)]
      eRegisterError_AccountExist = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eRegisterError_AccountInvalid", Value=2)]
      eRegisterError_AccountInvalid = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ELoginError")]
    public enum ELoginError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eLoginError_AccountNotExist", Value=1)]
      eLoginError_AccountNotExist = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eLoginError_PasswordIncorrect", Value=2)]
      eLoginError_PasswordIncorrect = 2
    }
  
}