//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: cmd_type.proto
namespace PROTO_CMD_TYPE
{
    [global::ProtoBuf.ProtoContract(Name=@"CMD_TYPE")]
    public enum CMD_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ROOM_MAIN", Value=10)]
      CMD_TYPE_ROOM_MAIN = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ROLE", Value=11)]
      CMD_TYPE_ROLE = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_SETTING", Value=12)]
      CMD_TYPE_SETTING = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_EMAIL", Value=13)]
      CMD_TYPE_EMAIL = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_CHAT", Value=14)]
      CMD_TYPE_CHAT = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ITEM", Value=15)]
      CMD_TYPE_ITEM = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_DIAMOND", Value=16)]
      CMD_TYPE_DIAMOND = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_WEAPONS", Value=17)]
      CMD_TYPE_WEAPONS = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_MERCENARY", Value=18)]
      CMD_TYPE_MERCENARY = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_CHAPTER", Value=19)]
      CMD_TYPE_CHAPTER = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_SQUADRON", Value=20)]
      CMD_TYPE_SQUADRON = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_SIGNIN", Value=21)]
      CMD_TYPE_SIGNIN = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_SHOP", Value=22)]
      CMD_TYPE_SHOP = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_FRIEND", Value=23)]
      CMD_TYPE_FRIEND = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_TASK", Value=24)]
      CMD_TYPE_TASK = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_VIP", Value=25)]
      CMD_TYPE_VIP = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ACTIVITY", Value=26)]
      CMD_TYPE_ACTIVITY = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_HEAD_ICON", Value=27)]
      CMD_TYPE_HEAD_ICON = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_RECHARGE", Value=28)]
      CMD_TYPE_RECHARGE = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_GIFTCODE", Value=29)]
      CMD_TYPE_GIFTCODE = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_RECHARGE_ACTIVITY", Value=30)]
      CMD_TYPE_RECHARGE_ACTIVITY = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_MILITARY", Value=31)]
      CMD_TYPE_MILITARY = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_RANKING", Value=32)]
      CMD_TYPE_RANKING = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_LOGINREWARD", Value=33)]
      CMD_TYPE_LOGINREWARD = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_EXTREME_CHALLENGE", Value=34)]
      CMD_TYPE_EXTREME_CHALLENGE = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ACTIVITIES_BATTLE", Value=35)]
      CMD_TYPE_ACTIVITIES_BATTLE = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_GAMELOG", Value=36)]
      CMD_TYPE_GAMELOG = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_FUNCTIONOPEN", Value=37)]
      CMD_TYPE_FUNCTIONOPEN = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_MULTI_PVE", Value=38)]
      CMD_TYPE_MULTI_PVE = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_PREDEFINESQUADRON", Value=39)]
      CMD_TYPE_PREDEFINESQUADRON = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_LUCKY_GOLD", Value=40)]
      CMD_TYPE_LUCKY_GOLD = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_OPENSERVER7DAY", Value=41)]
      CMD_TYPE_OPENSERVER7DAY = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_KINGOFPOSITION", Value=42)]
      CMD_TYPE_KINGOFPOSITION = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_DISCOUNT", Value=43)]
      CMD_TYPE_DISCOUNT = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_TOPRANKING", Value=44)]
      CMD_TYPE_TOPRANKING = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ACTIVITY_TASK", Value=45)]
      CMD_TYPE_ACTIVITY_TASK = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_CUMULATIVEONLINE", Value=46)]
      CMD_TYPE_CUMULATIVEONLINE = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ARMY_FRAME", Value=47)]
      CMD_TYPE_ARMY_FRAME = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_SKILL", Value=48)]
      CMD_TYPE_SKILL = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ARMY_GROUP_BOSS", Value=49)]
      CMD_TYPE_ARMY_GROUP_BOSS = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ARMY_WAR_COLLEGE", Value=50)]
      CMD_TYPE_ARMY_WAR_COLLEGE = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_COMMON", Value=98)]
      CMD_TYPE_COMMON = 98,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ACTION", Value=99)]
      CMD_TYPE_ACTION = 99,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_BATTLE_CHECK", Value=100)]
      CMD_TYPE_BATTLE_CHECK = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_AI", Value=101)]
      CMD_TYPE_AI = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_WORLDBOSS", Value=102)]
      CMD_TYPE_WORLDBOSS = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_CUSTOM_SQUADRON", Value=103)]
      CMD_TYPE_CUSTOM_SQUADRON = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_TYPE_ACTION_ARMY", Value=104)]
      CMD_TYPE_ACTION_ARMY = 104
    }
  
}